# -*- coding: utf-8 -*-
"""3. Trans_Meet_Linked_Other.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UQu2ToPefgR-HaVDV6mWJvL9hcoIILW
"""

#@title 🚀 **Start AI Transcription & Content Generation (All-in-One Version)**

#@markdown ### **1. Configuration**
#@markdown Enter the name of the main project folder in your Google Drive.
main_project_folder = 'MyTranscriptions' #@param {type:"string"}

#@markdown ---
#@markdown ### **2. Select Language & Model**
#@markdown **Select the language of your audio file.** This prevents errors.
audio_language = 'English' #@param ["English", "Spanish", "French", "German", "Italian", "Portuguese", "Dutch", "Russian", "Japanese", "Chinese", "Hindi"]
#@markdown Choose the model for transcription. "medium" is a good balance of speed & accuracy.
transcription_model_size = 'medium' #@param ["tiny", "base", "small", "medium", "large-v2"]

#@markdown ---
#@markdown ### **3. Select Features to Enable**
#@markdown Check the boxes for any additional documents you want the AI to create.
generate_meeting_notes = True #@param {type:"boolean"}
generate_content_ideas = True #@param {type:"boolean"}
generate_meeting_analysis = True #@param {type:"boolean"}


#@markdown ---
#@markdown ### **4. Click the Play Button!**
#@markdown This will start the entire process.

# ===============================================================
# SCRIPT - DO NOT EDIT BELOW THIS LINE
# ===============================================================
import os
import glob
import shutil
import time
import sys
import re
from google.colab import drive
from google.colab import userdata
import torch
import gc
import importlib

print("✅ Workflow Initiated...")
start_time = time.time()

# --- Step 1: Install Dependencies ---
print("\n[Step 1/8] Installing software dependencies...")
try:
    if importlib.util.find_spec("whisper") is None:
        os.system('pip install -q git+https://github.com/openai/whisper.git > /dev/null 2>&1')
    if generate_meeting_notes or generate_content_ideas or generate_meeting_analysis:
        if importlib.util.find_spec("google.generativeai") is None:
            os.system('pip install -q google-generativeai > /dev/null 2>&1')
    if not shutil.which("ffmpeg"):
        os.system('sudo apt-get -qq -y install ffmpeg > /dev/null 2>&1')
    import whisper
    if generate_meeting_notes or generate_content_ideas or generate_meeting_analysis:
        import google.generativeai as genai
    print(" Done.")
except Exception as e:
    print(f"\n❌ A critical error occurred during installation: {e}")
    sys.exit()

# --- Step 2: Connect to Google Drive ---
print("[Step 2/8] Connecting to Google Drive...", end="")
try:
    drive.mount('/content/drive', force_remount=True)
    print(" Done.")
except Exception as e:
    raise SystemExit(f"\n     ERROR: Could not connect to Google Drive. {e}")

# --- Step 3: Configure Gemini API ---
print("[Step 3/8] Configuring Gemini AI...")
GEMINI_API_KEY = None
MAX_RETRIES = 3
for attempt in range(MAX_RETRIES):
    try:
        GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
        genai.configure(api_key=GEMINI_API_KEY)
        print("   - Gemini AI configured successfully.")
        break # Exit loop if successful
    except Exception as e:
        print(f"   - Attempt {attempt + 1}/{MAX_RETRIES} failed: {e}")
        if attempt < MAX_RETRIES - 1:
            time.sleep(2) # Wait before retrying
        else:
            print("\n   - ⚠️ WARNING: Could not configure Gemini after multiple attempts. AI content generation will be skipped.")
            GEMINI_API_KEY = None # Ensure it's None if all retries fail

def get_gemini_response(prompt, model_name="gemini-1.5-flash-latest"):
    if not GEMINI_API_KEY: return "Skipped: Gemini API Key not available."
    try:
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"ERROR generating content: {e}"

# --- Step 4: Find Files to Process ---
print("[Step 4/8] Searching for new files to process (checking all subfolders)...")
drive_root = '/content/drive/MyDrive'
project_path = os.path.join(drive_root, main_project_folder)
TRANSCRIPTS_FOLDER_NAME = '01_Completed_Transcripts'
AI_CONTENT_FOLDER_NAME = '02_AI_Generated_Content'
PROCESSED_FOLDER_NAME = '03_Processed_Audio'

supported_extensions = ["*.mp3", "*.wav", "*.mp4", "*.m4a"]
all_potential_files = []
for ext in supported_extensions:
    search_path = os.path.join(project_path, '**', ext)
    all_potential_files.extend(glob.glob(search_path, recursive=True))

files_to_process = []
for file_path in all_potential_files:
    parent_dir = os.path.dirname(file_path)
    if any(output_folder in file_path for output_folder in [TRANSCRIPTS_FOLDER_NAME, AI_CONTENT_FOLDER_NAME, PROCESSED_FOLDER_NAME]):
        continue
    original_filename = os.path.basename(file_path)
    base_filename_no_ext = os.path.splitext(original_filename)[0]
    expected_transcript_path = os.path.join(parent_dir, TRANSCRIPTS_FOLDER_NAME, f"{base_filename_no_ext}_transcript.txt")
    if not os.path.exists(expected_transcript_path):
        files_to_process.append(file_path)
    else:
        print(f"   - Skipping '{original_filename}' (transcript already exists).")
files_to_process = list(set(files_to_process))

# --- Step 5, 6, 7 & 8: Process Files in Stages for Stability ---
if not files_to_process:
    print(f"✅ No new audio/video files found to process.")
else:
    print(f"   Found {len(files_to_process)} new file(s) to process. Starting...\n" + ("-" * 50))

    # STAGE 1: Transcription
    print(f"[Step 5/8] STAGE 1: Transcribing all audio files...")
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    gc.collect()
    try:
        transcription_model = whisper.load_model(transcription_model_size)
        print(f"   - Loaded '{transcription_model_size}' model successfully.")
    except Exception as e:
        raise SystemExit(f"\n     ERROR: Could not load transcription model. Did you enable GPU? {e}")

    LANG_MAP = {"English": "en", "Spanish": "es", "French": "fr", "German": "de", "Italian": "it", "Portuguese": "pt", "Dutch": "nl", "Russian": "ru", "Japanese": "ja", "Chinese": "zh", "Hindi": "hi"}
    lang_code = LANG_MAP.get(audio_language, "en")

    for file_path in files_to_process:
        original_filename = os.path.basename(file_path)
        base_filename_no_ext = os.path.splitext(original_filename)[0]
        parent_dir = os.path.dirname(file_path)
        print(f"   ▶️  Processing: {original_filename}...")

        transcript_output_path = os.path.join(parent_dir, TRANSCRIPTS_FOLDER_NAME)
        processed_audio_folder_path = os.path.join(parent_dir, PROCESSED_FOLDER_NAME)
        os.makedirs(transcript_output_path, exist_ok=True)
        os.makedirs(processed_audio_folder_path, exist_ok=True)
        try:
            print(f"     - Transcribing audio...", end="")
            whisper_result = transcription_model.transcribe(file_path, language=lang_code)
            transcript_text = whisper_result["text"]
            transcript_filename = os.path.join(transcript_output_path, f"{base_filename_no_ext}_transcript.txt")
            with open(transcript_filename, "w", encoding="utf-8") as f: f.write(transcript_text)
            print(" Done.")

            destination_audio_path = os.path.join(processed_audio_folder_path, original_filename)
            shutil.move(file_path, destination_audio_path)
            print("     ✅ Success: Original file archived.")
        except Exception as e:
            print(f"     ❌ ERROR processing {original_filename}: {e}")

    # Free up memory
    print("\n   - Releasing transcription model from memory...")
    del transcription_model
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    print("     - Memory freed.")


    # STAGE 2: AI Content Generation
    print(f"\n[Step 8/8] STAGE 2: Generating AI content...")
    for file_path in files_to_process: # Loop through the original list of processed files
        original_filename = os.path.basename(file_path)
        base_filename_no_ext = os.path.splitext(original_filename)[0]
        parent_dir = os.path.dirname(file_path)

        transcript_output_path = os.path.join(parent_dir, TRANSCRIPTS_FOLDER_NAME)
        notes_output_path = os.path.join(parent_dir, AI_CONTENT_FOLDER_NAME, 'Meeting_Notes')
        ideas_output_path = os.path.join(parent_dir, AI_CONTENT_FOLDER_NAME, 'Content_Ideas')
        analysis_output_path = os.path.join(parent_dir, AI_CONTENT_FOLDER_NAME, 'Meeting_Analysis')

        for folder in [notes_output_path, ideas_output_path, analysis_output_path]:
            os.makedirs(folder, exist_ok=True)

        transcript_filename = os.path.join(transcript_output_path, f"{base_filename_no_ext}_transcript.txt")
        try:
            with open(transcript_filename, 'r', encoding='utf-8') as f:
                transcript_for_ai = f.read()

            if generate_meeting_notes:
                print(f"   ▶️  Generating meeting notes for {original_filename}...")
                prompt = f"""Analyze the meeting transcript below and create a clear, structured meeting summary in Markdown format.

                Your output should include the following four sections:
                - A `# Summary` section with a concise paragraph stating the meeting’s main purpose and key outcomes.
                - A `## Key Decisions` section with a bulleted list of any important decisions that were made.
                - A `## Action Items` section using a bulleted list for all tasks, specifying who is responsible (e.g., `**Person:** Action`).
                - A `## Next Steps` section outlining what will happen next.

                Here is the transcript:
                ---
                {transcript_for_ai}
                ---
                """
                notes = get_gemini_response(prompt)
                notes_filename = os.path.join(notes_output_path, f"{base_filename_no_ext}_meeting_notes.md")
                with open(notes_filename, "w", encoding="utf-8") as f: f.write(notes)
                print("     - Done.")

            if generate_content_ideas:
                print(f"   ▶️  Generating content ideas for {original_filename}...")
                prompt = f"""Act as a content strategist. Analyze the following meeting transcript and identify 5-7 distinct, interesting, or surprising insights that could be turned into a LinkedIn post.

                For each idea, provide:
                - A short, catchy title or hook.
                - A one-sentence summary of the core lesson or point.

                Format the output as a numbered list.

                Here is the transcript:
                ---
                {transcript_for_ai}
                ---
                """
                ideas = get_gemini_response(prompt)
                ideas_filename = os.path.join(ideas_output_path, f"{base_filename_no_ext}_content_ideas.md")
                with open(ideas_filename, "w", encoding="utf-8") as f: f.write(ideas)
                print("     - Done.")

            if generate_meeting_analysis:
                print(f"   ▶️  Generating meeting analysis for {original_filename}...")
                prompt = f"""You are a meeting productivity analyst. Based on the transcript provided below, perform two distinct analyses and provide a score for each.

                **Analysis 1: Could This Have Been an Email? (0–100%)**
                Evaluate how necessary real-time interaction was. A high score means it was mostly one-way information sharing. A low score means collaboration was essential.
                - **Email-ability Score:** [Provide score here]
                - **Justification:** [Provide one-paragraph reasoning for your score.]

                **Analysis 2: Meeting Quality Score (0–10)**
                Assess the effectiveness of the meeting. Give points for each element that was clearly present: Purpose Stated (+2), Engaged Discussion (+2), Decisions Made (+3), Action Items Assigned (+3).
                - **Meeting Quality Score:** [Provide score here]
                - **Explanation:** [Provide one-paragraph explanation, highlighting what worked or what was missing.]

                Here is the transcript to analyze:
                ---
                {transcript_for_ai}
                ---
                """
                analysis = get_gemini_response(prompt)
                analysis_filename = os.path.join(analysis_output_path, f"{base_filename_no_ext}_meeting_analysis.md")
                with open(analysis_filename, "w", encoding="utf-8") as f: f.write(analysis)
                print("     - Done.")
        except Exception as e:
            print(f"     ❌ ERROR generating content for {original_filename}: {e}")

total_time = time.time() - start_time
print(f"\n🏁 All tasks complete! Total time: {total_time:.2f} seconds.")

"""# 🚀 AI Transcription & Content Generation (All-in-One)

This Google Colab notebook provides an automated workflow to transcribe audio/video files and generate AI-powered content based on the transcriptions.

## ✨ Features

- **Multilingual Transcription**: Automatically transcribes audio/video files using OpenAI's Whisper model, supporting various languages.
- **Google Drive Integration**: Connects to your Google Drive to find new media files and save processed outputs.
- **Intelligent Content Generation**: Leverages Google's Gemini AI to create:
    - **Meeting Notes**: Structured summaries from meeting transcripts.
    - **Content Ideas**: Suggestions for LinkedIn posts or other content based on discussions.
    - **Meeting Analysis**: Provides insights into meeting effectiveness (e.g., 'Could This Have Been an Email?' score, 'Meeting Quality Score').
- **Automated File Management**: Organizes your files by moving processed audio to a dedicated folder and storing transcripts and AI-generated content in structured subdirectories.

## 📝 How to Use

1.  **Open in Google Colab**: Open this notebook in Google Colab.
2.  **Configure Parameters**: In the first code cell, adjust the following parameters:
    -   `main_project_folder`: The name of your main project folder in Google Drive where your audio/video files are located.
    -   `audio_language`: Select the language of your audio files for accurate transcription.
    -   `transcription_model_size`: Choose a Whisper model size (e.g., 'medium' for a good balance).
    -   Check the boxes for `generate_meeting_notes`, `generate_content_ideas`, and `generate_meeting_analysis` if you want these AI features enabled.
3.  **Run the Cell**: Click the 'Play' button (▶️) on the first code cell to start the entire process.
4.  **Authorize Google Drive**: Follow the prompts to authorize Google Drive access.
5.  **Provide Gemini API Key**: Ensure your `GEMINI_API_KEY` is set in Google Colab secrets. If not, the AI content generation steps will be skipped.

## 📂 Output Structure

Within your `main_project_folder` (or the folder where your audio files reside), the notebook will create the following subfolders:

-   `01_Completed_Transcripts`: Contains `.txt` files of the transcribed audio.
-   `02_AI_Generated_Content`: Contains subfolders for:
    -   `Meeting_Notes`: Markdown files with meeting summaries.
    -   `Content_Ideas`: Markdown files with content ideas.
    -   `Meeting_Analysis`: Markdown files with meeting analysis.
-   `03_Processed_Audio`: The original audio/video files are moved here after processing.

## ⚠️ Important Notes

-   **GPU Usage**: For faster transcription, ensure you have a GPU runtime enabled in Colab (Runtime > Change runtime type > GPU).
-   **Gemini API Key**: A valid Gemini API key is crucial for AI content generation. If not provided or invalid, only transcription will occur.
-   **Supported Formats**: The notebook supports `.mp3`, `.wav`, `.mp4`, and `.m4a` file formats.
"""